"""empty message

Revision ID: 540e2b8d5d0b
Revises: 
Create Date: 2023-03-30 21:45:11.800953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540e2b8d5d0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_date', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('updated_date')

    # ### end Alembic commands ###
